#!/bin/bash
if [ "$(id -un)" != "abuseio" ]; then
  echo "This script must be run as user 'abuseio'." >&2
  exit 1
fi
for file in `find extra/notifier-samples/ -type f | sort | grep eml | grep -v disabled`
  do
    echo "pushing $file into queue"
    cat $file | php -q artisan email:receive
done
