<?php

use Illuminate\Database\Seeder;
use AbuseIO\ICF;

class NetblocksTableSeeder extends Seeder
{

    public function run()
    {

        DB::table('netblocks')->delete();

        $netblocks = array(
            [
                'id' => 1,
                'first_ip' => ICF::inet_ptoi('0.0.0.0'),
                'last_ip' => ICF::inet_ptoi('255.255.255.255'),
                'description' => 'This is a description',
                'contact_id' => 1,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 2,
                'first_ip' => ICF::inet_ptoi('10.0.2.0'),
                'last_ip' => ICF::inet_ptoi('10.0.2.255'),
                'description' => 'This is a description',
                'contact_id' => 2,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 3,
                'first_ip' => ICF::inet_ptoi('10.0.3.0'),
                'last_ip' => ICF::inet_ptoi('10.0.3.255'),
                'description' => 'This is a description',
                'contact_id' => 2,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 4,
                'first_ip' => ICF::inet_ptoi('2001:0000:0000:0000:0000:0000:0000:0000'),
                'last_ip' => ICF::inet_ptoi('2001:ffff:ffff:ffff:ffff:ffff:ffff:ffff'),
                'description' => 'This is a description',
                'contact_id' => 1,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 5,
                'first_ip' => ICF::inet_ptoi('2001:0666:0000:0000:0000:0000:0000:0000'),
                'last_ip' => ICF::inet_ptoi('2001:0666:ffff:ffff:ffff:ffff:ffff:ffff'),
                'description' => 'This is a description',
                'contact_id' => 2,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 6,
                'first_ip' => ICF::inet_ptoi('2001:0777:0000:0000:0000:0000:0000:0000'),
                'last_ip' => ICF::inet_ptoi('2001:0777:ffff:ffff:ffff:ffff:ffff:ffff'),
                'description' => 'This is a description',
                'contact_id' => 3,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 7,
                'first_ip' => ICF::inet_ptoi('10.0.4.0'),
                'last_ip' => ICF::inet_ptoi('10.0.4.255'),
                'description' => 'This is a description',
                'contact_id' => 2,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 8,
                'first_ip' => ICF::inet_ptoi('10.0.5.0'),
                'last_ip' => ICF::inet_ptoi('10.0.5.255'),
                'description' => 'This is a description',
                'contact_id' => 3,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 9,
                'first_ip' => ICF::inet_ptoi('10.0.6.0'),
                'last_ip' => ICF::inet_ptoi('10.0.6.255'),
                'description' => 'This is a description',
                'contact_id' => 3,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 10,
                'first_ip' => ICF::inet_ptoi('10.0.7.0'),
                'last_ip' => ICF::inet_ptoi('10.0.7.255'),
                'description' => 'This is a description',
                'contact_id' => 3,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 11,
                'first_ip' => ICF::inet_ptoi('10.0.8.0'),
                'last_ip' => ICF::inet_ptoi('10.0.8.255'),
                'description' => 'This is a description',
                'contact_id' => 3,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 12,
                'first_ip' => ICF::inet_ptoi('10.0.9.0'),
                'last_ip' => ICF::inet_ptoi('10.0.9.255'),
                'description' => 'This is a description',
                'contact_id' => 3,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 21,
                'first_ip' => ICF::inet_ptoi('10.1.11.0'),
                'last_ip' => ICF::inet_ptoi('10.1.11.255'),
                'description' => 'This is a description',
                'contact_id' => 11,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 22,
                'first_ip' => ICF::inet_ptoi('10.1.12.12'),
                'last_ip' => ICF::inet_ptoi('10.1.12.14'),
                'description' => 'This is a description',
                'contact_id' => 12,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 13,
                'first_ip' => ICF::inet_ptoi('10.1.13.0'),
                'last_ip' => ICF::inet_ptoi('10.1.13.255'),
                'description' => 'This is a description',
                'contact_id' => 13,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 14,
                'first_ip' => ICF::inet_ptoi('10.1.14.0'),
                'last_ip' => ICF::inet_ptoi('10.1.14.127'),
                'description' => 'This is a description',
                'contact_id' => 14,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 15,
                'first_ip' => ICF::inet_ptoi('10.1.15.0'),
                'last_ip' => ICF::inet_ptoi('10.1.15.255'),
                'description' => 'This is a description',
                'contact_id' => 15,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 16,
                'first_ip' => ICF::inet_ptoi('10.1.16.128'),
                'last_ip' => ICF::inet_ptoi('10.1.16.195'),
                'description' => 'This is a description',
                'contact_id' => 16,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 17,
                'first_ip' => ICF::inet_ptoi('10.1.17.0'),
                'last_ip' => ICF::inet_ptoi('10.1.17.255'),
                'description' => 'This is a description',
                'contact_id' => 17,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 18,
                'first_ip' => ICF::inet_ptoi('10.1.18.0'),
                'last_ip' => ICF::inet_ptoi('10.1.18.255'),
                'description' => 'This is a description',
                'contact_id' => 18,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 19,
                'first_ip' => ICF::inet_ptoi('10.1.19.0'),
                'last_ip' => ICF::inet_ptoi('10.1.19.255'),
                'description' => 'This is a description',
                'contact_id' => 19,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'id' => 20,
                'first_ip' => ICF::inet_ptoi('10.1.19.5'),
                'last_ip' => ICF::inet_ptoi('10.1.19.9'),
                'description' => 'This is a description',
                'contact_id' => 19,
                'enabled' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ]
        );

        DB::table('netblocks')->insert($netblocks);
    }
}
