site_name: AbuseIO
repo_url: https://github.com/AbuseIO/AbuseIO
site_description: Abusemanagement tools
site_author: AbuseIO
pages:
- 'Introduction': 'index.md'
- 'Installation': 'installation.md'
- 'Migrating from 3.x': 'migration.md'
- 'Main configuration': 'configuration-main.md'
- 'Parser configurations': 'configuration-parsers.md'
- 'License': 'license.md'
