<?php

namespace AbuseIO\Api;

class ErrorCodes
{
    const CODE_WRONG_ARGS = 'ERR_WRONGARGS';
    const CODE_NOT_FOUND = 'ERR_NOTFOUND';
    const CODE_INTERNAL_ERROR = 'ERR_INTERNALERROR';
    const CODE_UNAUTHORIZED = 'ERR_NOTATHORIZED';
    const CODE_FORBIDDEN = 'ERR_FORBIDDEN';
    const CODE_SUCCESSFULL = 'SUCCESSFULL';
}
