<?php

namespace AbuseIO\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Validator;

class BaseBrandRequest extends FormRequest
{

    protected function filterRulesForPresentFields(array $rules): array
    {
        $data = $this->all();
        $filtered = [];
        foreach ($rules as $field => $rule) {
            if (array_key_exists($field, $data) || $this->hasFile($field)) {
                $filtered[$field] = $rule;
            }
        }
        return $filtered;
    }

    protected function getValidatorInstance(): Validator
    {
        $validator = parent::getValidatorInstance(); // TODO: Change the autogenerated stub

        if ($this->wantsJson()) {
            $validator->setRules($this->filterRulesForPresentFields($validator->getRules()));
        }

        return $validator;
    }
}
