#!/bin/bash
echo caches
cd /opt/abuseio/
rm -rf bootstrap/cache/*.php
sudo -u abuseio php /opt/abuseio/artisan cache:clear
sudo -u abuseio php /opt/abuseio/artisan config:clear
sudo -u abuseio php /opt/abuseio/artisan view:clear
sudo -u abuseio php /opt/abuseio/artisan route:clear
sudo -u abuseio composer --working-dir=/opt/abuseio dump-autoload

echo reset permissions
cd /opt/abuseio
chown -R abuseio:abuseio .
chmod -R 777 storage/
chmod 775 bootstrap/cache/

echo rebuilding database
sudo -u abuseio php /opt/abuseio/artisan db:wipe
sudo -u abuseio php /opt/abuseio/artisan migrate --force

echo creating default user
sudo -u abuseio php /opt/abuseio/artisan user:create admin@isp.local --password=ispadmin
sudo -u abuseio php /opt/abuseio/artisan role:assign --role=admin --user=admin@isp.local

echo restart services
sudo systemctl restart abuseio_queue_collector
sudo systemctl restart abuseio_queue_email_incoming
sudo systemctl restart abuseio_queue_email_outgoing
sudo systemctl restart abuseio_queue_delegation

echo seeding database defaults
sudo -u abuseio php /opt/abuseio/artisan db:seed --force


echo seeding notifier samples
sudo -u abuseio /opt/abuseio/extra/notifier-samples/runall

