#!/bin/bash
echo stopping services
systemctl stop abuseio_queue_collector
systemctl stop abuseio_queue_email_incoming
systemctl stop abuseio_queue_email_outgoing
systemctl stop abuseio_queue_delegation

echo caches
rm -rf bootstrap/cache/*.php
sudo -u abuseio composer --working-dir=/opt/abuseio clear-cache
sudo -u abuseio php /opt/abuseio/artisan cache:clear
sudo -u abuseio php /opt/abuseio/artisan config:clear
sudo -u abuseio php /opt/abuseio/artisan view:clear
sudo -u abuseio php /opt/abuseio/artisan route:clear
sudo -u abuseio composer --working-dir=/opt/abuseio dump-autoload

cd /opt/abuseio
chown -R abuseio:abuseio .
chmod -R 777 storage/
chmod 775 bootstrap/cache/

echo restart services
sudo systemctl start abuseio_queue_collector
sudo systemctl start abuseio_queue_email_incoming
sudo systemctl start abuseio_queue_email_outgoing
sudo systemctl start abuseio_queue_delegation
